feat: create login and sign up forms
ave-mario/peach pull request #5
Opened 2019-05-24 07:38 UTC by jastapanda

WIP

2019-05-29 06:53 UTC, artyom-furmanov submitted a review, later dismissed

2019-05-31 07:49 UTC, VikaBondareva submitted a review, later dismissed

2019-05-31 09:52 UTC, underscorekadji requested changes

2019-05-31 09:52 UTC, underscorekadji commented on package.json
> +      "eslint --fix"
мне кажется что после --fix останутся измененные файлы которые просто так не войдут в коммит и требуется git add
`{
  "*.js": ["eslint --fix", "git add"]
}`

2019-05-31 09:52 UTC, underscorekadji commented on package.json
> +      "prettier --write"
тоже самое как и для eslint --fix

2019-05-31 09:52 UTC, underscorekadji commented on src/containers/sign_in.container.js
> +const loginCode = '123456'; // /////will redo after impl on server///////
Для комментариев которые подразумевают дальнейшие изменения следует использовать `// TODO: To do something`  и какой-нибудь плагин который подсвечивает их типа https://marketplace.visualstudio.com/items?itemName=wayou.vscode-todo-highlight

2019-05-31 09:52 UTC, underscorekadji commented on src/containers/sign_in.container.js
> +          loginCode,
плохая практика использовать глобальные объекты, лучше пробросить `(phoneNumber, loginCode)`

2019-05-31 09:52 UTC, underscorekadji commented on src/containers/sign_up.container.js
> +const email = '1234567@gmail.com'; // /////will redo after impl on server///////
аналогично с `loginCode`

2019-05-31 09:52 UTC, underscorekadji commented on src/services/get_auth_header.js
> +export default function getAuthHeader() {
если есть getter то можно сделать и setter

2019-06-04 13:45 UTC, VikaBondareva submitted a review, later dismissed

2019-06-04 13:46 UTC, artyom-furmanov submitted a review, later dismissed

2019-06-04 15:11 UTC, underscorekadji approved these changes

2019-06-04 15:18 UTC, VikaBondareva submitted a review, later dismissed

2019-06-04 22:29 UTC, underscorekadji requested changes

2019-06-04 22:29 UTC, underscorekadji commented on package.json
> +    "husky:pre-push": "npm run lint:fix",
если не ошибаюсь, фикс линтера перед пушем не внесет изменения в то что будет отправлено на origin

2019-06-04 22:29 UTC, underscorekadji commented on package.json
> +    "husky:pre-push": "npm run lint:fix",
лучше использовать просто проверку lint + ывполнение тестов, чтобы на CI никаких неожиданностей не произошло

2019-06-04 22:29 UTC, underscorekadji commented on src/index.js
> +axios.defaults.baseURL = 'http://localhost:3001/api/';
значение надо брать из `process.env`

2019-06-04 22:29 UTC, underscorekadji commented on src/sagas/sign_in.saga.js
> +      console.log(payload);
мои логин и пароль будут выведены в консоль? :)

2019-06-04 22:29 UTC, underscorekadji commented on src/sagas/sign_up.saga.js
> +      console.log(payload);
мои логин и пароль будут выведены в консоль? :)
именно поэтому пишут logger которых в процессе разработки выводит в консоль информацию для дебага, но при билде webpack удаляет его и проверяется тестом, что логгера в консоль в коде нет

2019-06-05 12:58 UTC, artyom-furmanov approved these changes

2019-06-05 13:27 UTC, VikaBondareva approved these changes

2019-06-05 13:32 UTC, underscorekadji approved these changes

2019-06-05 13:44 UTC, merged